[package]
name = "fsfilter"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
libbpf-rs = "0.24.8"
libc = "0.2.169"
regex = "1.11.1"

[build-dependencies]
libbpf-cargo = "0.24.8"

[package.metadata.libbpf]
prog_dir = "src/bpf"
